jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
      Prueba\InicialBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: PruebaInicialBundle:User, property: username }

    firewalls:
        #admin_area:
        #    provider: user_db
        #    pattern:    ^/admin
        #    http_basic: true
        #    logout: { path: /admin/logout, target: / }
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /contact, roles: ROLE_USER }
        - { path: /about, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      
      
     #********************************************************************************
     #             Todo lo de abajo estaba antes junto con las pruebas
     
     #   dev:
     #       pattern:  ^/(_(profiler|wdt)|css|images|js)/
     #       security: false

     #   login:
     #       pattern:  ^/demo/secured/login$
     #       security: false

     #   secured_area:
     #       pattern:    ^/demo/secured/
     #       form_login:
     #           check_path: _security_check
     #           login_path: _demo_login
     #       logout:
     #           path:   _demo_logout
     #           target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
