# src/Prueba/InicialBundle/Resources/config/config.yml
parameters:
    # dirección de correo electrónico para contacto del Blogger
    blogger_blog.emails.contact_email: no-direccion@dominio.com
    # Blogger max latest comments
    Prueba_blog.comments.latest_comment_limit: 10