PruebaInicialBundle_page:
    pattern:  /
    defaults: { _controller: PruebaInicialBundle:Default:index}
    requirements:
        _method:  GET
  
# src/Prueba/InicialBundle/Resources/config/routing.yml
PruebaInicialBundle_about:
    pattern:  /about
    defaults: { _controller: PruebaInicialBundle:Default:about }
    requirements:
        _method:  GET

# src/Prueba/InicialBundle/Resources/config/routing.yml
PruebaInicialBundle_contact:
    pattern:  /contact
    defaults: { _controller: PruebaInicialBundle:Default:contact }
    requirements:
        _method:  GET|POST

#PruebaInicialBundle_login:
#    pattern:   /login
#    defaults:  { _controller: PruebaInicialBundle:Security:login }
   
#PruebaInicialBundle_login_check:
#    pattern:   /login_check        


# src/Prueba/InicialBundle/Resources/config/routing.yml
PruebaInicialBundle_blog_show:
    pattern:  /{slug}
    defaults: { _controller: PruebaInicialBundle:Blog:show }
    requirements:
        _method:  GET
        #id: \d+
        
#De momento lo comento 
#show:
#    pattern: /show
#    defaults: { _controller: PruebaInicialBundle:Blog:show }

# src/Prueba/InicialBundle/Resources/config/routing.yml
PruebaInicialBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: PruebaInicialBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+