parameters:
#    prueba_inicial.example.class: Prueba\InicialBundle\Example

services:
#    prueba_inicial.example:
#        class: %prueba_inicial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
